package model

import (
	"time"

	"github.com/google/uuid"
)

// PostStatus represents the publication status
type PostStatus string

const (
	PostStatusDraft     PostStatus = "draft"
	PostStatusPending   PostStatus = "pending"   // In sandbox/moderation
	PostStatusPublished PostStatus = "published"
	PostStatusArchived  PostStatus = "archived"
	PostStatusRejected  PostStatus = "rejected"
)

// PostVisibility represents who can see the post
type PostVisibility string

const (
	VisibilityPublic      PostVisibility = "public"       // Everyone, indexed by Google
	VisibilityUnlisted    PostVisibility = "unlisted"     // Only via link, not indexed
	VisibilityMembersOnly PostVisibility = "members_only" // Registered users only
	VisibilityPrivate     PostVisibility = "private"      // Specific community/org only
)

// PostFormat represents the type of content
type PostFormat string

const (
	FormatDeepDive   PostFormat = "deep_dive"   // Long-form analysis
	FormatTutorial   PostFormat = "tutorial"    // How-to guide
	FormatNewsBrief  PostFormat = "news_brief"  // Short news
	FormatSeries     PostFormat = "series"      // Part of a series
	FormatCaseStudy  PostFormat = "case_study"  // Real-world case
	FormatDiscussion PostFormat = "discussion"  // Open discussion/question
)

// Post represents an article/post
type Post struct {
	ID              uuid.UUID      `json:"id" db:"id"`
	AuthorID        uuid.UUID      `json:"author_id" db:"author_id"`
	OrganizationID  *uuid.UUID     `json:"organization_id,omitempty" db:"organization_id"`
	CommunityID     *uuid.UUID     `json:"community_id,omitempty" db:"community_id"`
	SeriesID        *uuid.UUID     `json:"series_id,omitempty" db:"series_id"`
	SeriesOrder     *int           `json:"series_order,omitempty" db:"series_order"`

	// Content
	Title           string         `json:"title" db:"title"`
	Slug            string         `json:"slug" db:"slug"`
	Subtitle        string         `json:"subtitle" db:"subtitle"`
	Content         string         `json:"content" db:"content"`           // Tiptap JSON
	ContentHTML     string         `json:"content_html" db:"content_html"` // Rendered HTML
	ContentText     string         `json:"-" db:"content_text"`            // Plain text for search
	Excerpt         string         `json:"excerpt" db:"excerpt"`           // Short preview

	// Media
	CoverImageURL   string         `json:"cover_image_url" db:"cover_image_url"`
	OGImageURL      string         `json:"og_image_url" db:"og_image_url"` // For social sharing

	// Meta
	Language        string         `json:"language" db:"language"`
	Format          PostFormat     `json:"format" db:"format"`
	Status          PostStatus     `json:"status" db:"status"`
	Visibility      PostVisibility `json:"visibility" db:"visibility"`
	ReadingTime     int            `json:"reading_time" db:"reading_time"` // Minutes
	CanonicalURL    string         `json:"canonical_url" db:"canonical_url"`

	// Engagement (denormalized for performance)
	ViewsCount      int            `json:"views_count" db:"views_count"`
	ClapsCount      int            `json:"claps_count" db:"claps_count"`
	CommentsCount   int            `json:"comments_count" db:"comments_count"`
	BookmarksCount  int            `json:"bookmarks_count" db:"bookmarks_count"`
	SharesCount     int            `json:"shares_count" db:"shares_count"`

	// SEO
	MetaTitle       string         `json:"meta_title" db:"meta_title"`
	MetaDescription string         `json:"meta_description" db:"meta_description"`
	MetaKeywords    []string       `json:"meta_keywords" db:"meta_keywords"`

	// Timestamps
	CreatedAt       time.Time      `json:"created_at" db:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at" db:"updated_at"`
	PublishedAt     *time.Time     `json:"published_at,omitempty" db:"published_at"`
	DeletedAt       *time.Time     `json:"-" db:"deleted_at"`

	// Relations (loaded separately)
	Author          *User          `json:"author,omitempty"`
	Organization    *Organization  `json:"organization,omitempty"`
	Tags            []Tag          `json:"tags,omitempty"`
	Category        *Category      `json:"category,omitempty"`
}

// PostTranslation represents a translated version of a post
type PostTranslation struct {
	ID              uuid.UUID  `json:"id" db:"id"`
	PostID          uuid.UUID  `json:"post_id" db:"post_id"`
	Language        string     `json:"language" db:"language"`
	Title           string     `json:"title" db:"title"`
	Subtitle        string     `json:"subtitle" db:"subtitle"`
	Content         string     `json:"content" db:"content"`
	ContentHTML     string     `json:"content_html" db:"content_html"`
	IsAutoGenerated bool       `json:"is_auto_generated" db:"is_auto_generated"`
	CreatedAt       time.Time  `json:"created_at" db:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at" db:"updated_at"`
}

// Tag represents a hashtag/topic
type Tag struct {
	ID             uuid.UUID `json:"id" db:"id"`
	Name           string    `json:"name" db:"name"`           // #python
	Slug           string    `json:"slug" db:"slug"`           // python
	Description    string    `json:"description" db:"description"`
	IconURL        string    `json:"icon_url" db:"icon_url"`
	Color          string    `json:"color" db:"color"`
	PostsCount     int       `json:"posts_count" db:"posts_count"`
	FollowersCount int       `json:"followers_count" db:"followers_count"`
	CreatedAt      time.Time `json:"created_at" db:"created_at"`
}

// PostTag is a join table between posts and tags
type PostTag struct {
	PostID    uuid.UUID `json:"post_id" db:"post_id"`
	TagID     uuid.UUID `json:"tag_id" db:"tag_id"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
}

// Category represents a top-level section
type Category struct {
	ID          uuid.UUID `json:"id" db:"id"`
	Name        string    `json:"name" db:"name"`
	Slug        string    `json:"slug" db:"slug"`
	Description string    `json:"description" db:"description"`
	IconURL     string    `json:"icon_url" db:"icon_url"`
	Color       string    `json:"color" db:"color"`
	SortOrder   int       `json:"sort_order" db:"sort_order"`
	PostsCount  int       `json:"posts_count" db:"posts_count"`
	CreatedAt   time.Time `json:"created_at" db:"created_at"`
}

// Series represents a collection of related posts
type Series struct {
	ID          uuid.UUID  `json:"id" db:"id"`
	AuthorID    uuid.UUID  `json:"author_id" db:"author_id"`
	Title       string     `json:"title" db:"title"`
	Slug        string     `json:"slug" db:"slug"`
	Description string     `json:"description" db:"description"`
	CoverURL    string     `json:"cover_url" db:"cover_url"`
	PostsCount  int        `json:"posts_count" db:"posts_count"`
	IsCompleted bool       `json:"is_completed" db:"is_completed"`
	CreatedAt   time.Time  `json:"created_at" db:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at" db:"updated_at"`
}

// PostClap represents a clap (like) on a post
type PostClap struct {
	UserID    uuid.UUID `json:"user_id" db:"user_id"`
	PostID    uuid.UUID `json:"post_id" db:"post_id"`
	Count     int       `json:"count" db:"count"` // Users can clap multiple times (max 50)
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
}

// PostReaction represents emoji reactions on a post
type PostReaction struct {
	ID        uuid.UUID `json:"id" db:"id"`
	UserID    uuid.UUID `json:"user_id" db:"user_id"`
	PostID    uuid.UUID `json:"post_id" db:"post_id"`
	Emoji     string    `json:"emoji" db:"emoji"` // fire, unicorn, mind_blown, etc.
	CreatedAt time.Time `json:"created_at" db:"created_at"`
}

// Bookmark represents a saved post
type Bookmark struct {
	UserID    uuid.UUID  `json:"user_id" db:"user_id"`
	PostID    uuid.UUID  `json:"post_id" db:"post_id"`
	Note      string     `json:"note" db:"note"`
	FolderID  *uuid.UUID `json:"folder_id,omitempty" db:"folder_id"`
	CreatedAt time.Time  `json:"created_at" db:"created_at"`
}

// BookmarkFolder represents a collection of bookmarks
type BookmarkFolder struct {
	ID        uuid.UUID `json:"id" db:"id"`
	UserID    uuid.UUID `json:"user_id" db:"user_id"`
	Name      string    `json:"name" db:"name"`
	IsPrivate bool      `json:"is_private" db:"is_private"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
}
